### ISSUE TITLE
acdd_ext date_created_type does not apply types for second mmd:update 

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mmd-tools#132]
The following ACDD attributes: 		
```
:date_created = "2021-09-02,2021-09-08" ;
:date_created_type = "Created,Minor modification" ;

```
Translates by py-mmd-tools to:
```
<mmd:last_metadata_update>
  <mmd:update>
    <mmd:datetime>2021-09-02</mmd:datetime>
    <mmd:type>Created</mmd:type>
  </mmd:update>
  <mmd:update>
    <mmd:datetime>2021-09-08</mmd:datetime>
  </mmd:update>
</mmd:last_metadata_update>
```

Tried changing to:
`:date_created_type = "Created,Created" ;`

But still results in type-less update for 2021-09-08
```
<mmd:last_metadata_update>
  <mmd:update>
    <mmd:datetime>2021-09-02</mmd:datetime>
    <mmd:type>Created</mmd:type>
  </mmd:update>
  <mmd:update>
    <mmd:datetime>2021-09-08</mmd:datetime>
  </mmd:update>
</mmd:last_metadata_update>
```

**Comment by johtoblan** [comment]
This in turn causes failure at DMCI-validation, since mmd:type is required for mmd:last_metadata_update

**Comment by mortenwh** [comment]
I think `date_created` should only be used once. For updates, you should use `date_metadata_modified`. I'm making some tests now to check that it works as expected..

**Comment by johtoblan** [comment]
I see, may have misunderstood the repetition comment in https://metno.github.io/data-management-handbook/#acdd-elements

**Comment by mortenwh** [comment]
I'm pushing a PR now. Due to the design of `mmd_elements.yaml`, the repetition comments are the same for `date_created` and `date_metadata_modified` as well as for the respective types. That's not so easy to fix, so let's just assume that people understand that a dataset is only created once...
