### ISSUE TITLE
Using default value Active for metadata_status still reported

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mmd-tools#133]
The check added in PR #129 does not work I think.

`/home/johannestl/.conda/envs/validate/lib/python3.8/site-packages/py_mmd_tools/nc_to_mmd.py:929: UserWarning: 
	id ACDD attribute is missing - created metadata_identifier MMD element as uuid.
	Using default value Active for metadata_status
  warnings.warn("\n\t"+"\n\t".join(self.missing_attributes['warnings']))
`

**Comment by johtoblan** [comment]
This is a minor issue though

**Comment by mortenwh** [comment]
Are you sure you're using the correct version (latest in master)? There's no warning issued on line 929, and the message should have been removed..?

**Comment by johtoblan** [comment]
My bad. This works as intended
