### ISSUE TITLE
Architecture diagram for Frost client

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mmd-tools#156]

**Comment by mortenwh** [comment]
@johtoblan - can you review https://s-enda.pages.met.no/data-management-architecture/#_context_overview_at_met and https://s-enda.pages.met.no/data-management-architecture/#_frost_datasets

**Comment by johtoblan** [comment]
Should the Metadata Services system be described in detail in the frost-datasets container diagram? otherwise LGTM

**Comment by mortenwh** [comment]
Done in gitlab
