### ISSUE TITLE
Times should be in correct ISO8601 format

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#164]
Currently, we do not check the format. This needs to be implemented.

**Comment by mortenwh** [comment]
I think this is solved in #158

**Comment by mortenwh** [comment]
The solution needs to be reverted since the time format in `mmd_strict.xsd` follows `xs:date` definition, which does not seem to be following ISO8601. This needs to be checked, though..

**Comment by johtoblan** [comment]
Needs to be confirmed, but possibly solved
