### ISSUE TITLE
Update monitoring C4 container diagram

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#166]
What do the metadata checker and geohealthcheck read from the services? (Unclear C4 diagrams)

**Comment by charlienegri** [comment]
the text in the bottom boxes is the same in all them, is that meant to be so?

**Comment by charlienegri** [comment]
the ghc instance https://ghc.met.no/resources?lang=en&tag=S-ENDA (is this what Service Status and QoS Checker is meant to be? or is that broader?) checks on https://csw-dev.s-enda.k8s.met.no and https://csw-staging.s-enda.k8s.met.no/ basically, am not sure how to translate this in the context of that diagram

**Comment by mortenwh** [comment]
Yes, that's the right diagram. The text is "the OGC web services are monitored by GHC, whereas the infrastructure is monitored by prometheus". Maybe it becomes more clear if we write "the interface is monitored by GHC, whereas the infrastructure is monitored by prometheus"? Alternatively, maybe this should be in the arrow text, like "[ghc] -- reads XX from the OPeNDAP interface of -->  [Data distribution services]" etc.

Your last comment; this is ok (we need to monitor prod as well but this does not need to be shown in the drawings).

What this issue was mostly about, was that the arrows between the boxes have incomplete text. We need to express what they read/post/push, and with which protocol.

**Comment by mortenwh** [comment]
closed in gitlab
