### ISSUE TITLE
The ACDD naming authority should be extracted from the MMD metadata identifier field

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#167]
The translation of the `metadata_identifier` field in `mmd_to_nc.py` is not picking up the `naming_authority` but stores the entire `metadata_identifier` in the ACDD id attribute. The `metadata_identifier` should be split into ACDD `naming_authority` and `id`. We may need to create a special case function for this.

**Comment by mortenwh** [comment]
Few things:
1: it seems strange that it tests `mmd_element` but uses `element` as argument... is this correct? (that was just something I noted now)
2: hm, yes - it seems to be solved... is it also tested? Maybe I solved it in another issue...

**Comment by jo-asplin-met-no** [comment]
Looks like the argument `element` is some kind of instance object that contains extra data in addition to just the name, whereas `mmd_element` is just the common name for those instances (in this case the string 'metadata_identifier'). So looks correct to me.
