### ISSUE TITLE
MMD validator for netcdf files

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#20]
Use code in metno/mmd. Consider copying or moving that code to py-mmd-tools, then refine, write unit tests etc.

**Comment by ElodieFZ** [comment]
An MMD validator would be a script that checks that a netCDF files contains all the metadata necessary to create a valid MMD file? If that's the case, I think that it is something that should be part of a script that creates an MMD file from a netcdf (mostly already existing in the mmd repo: mmd_utils/nc_to_mmd.py). If we create a different script, it will be very similar to this one, as most of the job is to open the netcdf file and read the metadata. The only difference I see is whether the output MMD file is written or not.

There is also a script in mmd/mmd_utils a validator for MMD files (checkMMD.py). That's the one I want to use for #288

What do you think @mortenwh ?

**Comment by mortenwh** [comment]
Yes, it should check the provided netcdf files. It is important that it can be used both as part of the CI process, and independently to map the status of, e.g., files on thredds.met.no. Sounds good to also use it as part of the process to write MMD files. It may be enough to refactor some old code to be able to use it for these three (or more) scenarios.
