### ISSUE TITLE
Allow parantheses in the ACDD attributes to use for short name

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#212]
See `mmd_elements.yaml`: If each substring includes a keyword in parantheses, the content within the paranthesis is interpreted as the short name for the project while the rest is the long name, e.g., 'Nansen Legacy (NLEG)'. --- this requires a modification of `nc_to_mmd.py`.. Similar for the "platform" and "instrument" elements.

Change to the parenthesis form for the following attributes:

- [x] project
- [x] platform
- [x] instrument
- [x] institution
- [x] alternate_identifier [<url> (<type>)]

Change in mmd_elements.yaml
- [x] date_created (no need to specify date_created_type in parenthesis, just set the type to "Created" in nc_to_mmd.py)

Also, update/remove some not needed accd extra attributes (from the file mmd_elements.yaml):
- [x] license_identifier
- [x] institution_short_name
- [x] alternate_identifier_type
- [x] date_created_type
- [x] remove date_metadata_modified
- [x] date_metadata_modified_type

**Comment by mortenwh** [comment]
Probably.. Would it be possible to interpret the description in any other way? If so, we might need to include an example.

**Comment by charlienegri** [comment]
I finished the first part, for the next part, what does removing licence_identifier mean in practice?
the current 'get_licence` uses that field to fill in data['identifier']:   
`acdd_license_id = list(mmd_element['identifier']['acdd_ext'].keys())[0]`  
```
        acdd_license = list(mmd_element['resource']['acdd'].keys())[0]
        acdd_license_id = list(mmd_element['identifier']['acdd_ext'].keys())[0]
        license = getattr(ncin, acdd_license).split('(')
        license_url = license[0].strip()
        # validate url
        if not valid_url(license_url):
            # Try deprecated attribute name
            if 'license_resource' in ncin.ncattrs():
                license_url = ncin.license_resource
            if not valid_url(license_url):
                self.missing_attributes['errors'].append(
                    '"%s" is not a valid url' % license_url)
                return data
            else:
                data = {'resource': license_url}
                old_version = True
                self.missing_attributes['warnings'].append(
                    '"license_resource" is a deprecated attribute')
        else:
            data = {'resource': license_url}
        if len(license) > 1:
            data['identifier'] = license[1][0:-1]
        else:
            if acdd_license_id not in ncin.ncattrs():
                self.missing_attributes['warnings'].append(
                    '%s is a recommended attribute' % acdd_license_id
                )
                if old_version:
                    data['identifier'] = ncin.license
            else:
                data['identifier'] = getattr(ncin, acdd_license_id)
        return data
```        
does this mean that the `data['identifier']` field also needs to go? and is `license_resource` still a deprecated attribute?

**Comment by mortenwh** [comment]
the ACDD field "license" should be provided as "resource (identifier)", e.g., "https://spdx.org/licenses/CC-BY-4.0.html (CC-BY4.0)". So, the returned dict should be:
```
data["resource"] = "https://spdx.org/licenses/CC-BY-4.0.html"
data["identifier"] = "CC-BY-4.0"
```
Since it is provided as "resource (identifier)", the `acdd_ext` field (i.e., `license_identifier`) under license->identifier can be removed, right?

`license_resource` is not needed either, since we just use the `license` attribute.

**Comment by charlienegri** [comment]
so 
```
if len(license) > 1:
            data['identifier'] = license[1][0:-1]
        else:
```
the else should then just thrown an error here?
