### ISSUE TITLE
Loosen up criterium of controlled vocabulary use in ACDD references attribute

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#218]
Currently, the `get_related_information` function has a strict check on (a copy of) the controlled vocabulary from MMD. I suggest to loosen up a bit to allow a different use of upper and lower case. This can easily be handled in the function.

**Comment by johtoblan** [comment]
Should controlled vocabularies accept different capitalization? Users guide == Users Guide == users guide?
