### ISSUE TITLE
Add landing page information when creating mmd

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mmd-tools#225]

**Comment by johtoblan** [comment]
data.met.no to be added to all xml-files with no.met naming authority. Implement as Lookup table naming authority -> landing page?

DMCI will handle -dev and -staging envs.

**Comment by charlienegri** [comment]
is the landing page attribute meant to be basically a url in `dataset_citation`?
and if yes, does it mean that in `nc_to_mmd.py` for example, in the function `to_mmd` it will be appended to potentially existing to self.metadata['dataset_citation']['url'] (if `self.metadata['metadata_identifier'][0]` == "no.met"), or maybe I am misunderstanding at what level you want this to be created?

**Comment by mortenwh** [comment]
It should be under `related_information`:
```
<related_information>
    <type>Dataset landing page</type>
    <resource>URI</resource>
</related_information>
```

That will be `self.metadata['related_information']`. See https://github.com/metno/py-mmd-tools/blob/master/py_mmd_tools/templates/mmd_template.xml to understand how it is used with jinja:

```
  {% if data['related_information'] %}
    {% for related_info in data['related_information'] %}
  <mmd:related_information>
    <mmd:type>{{ related_info['type'] }}</mmd:type>
    <mmd:description>{{ related_info['description'] }}</mmd:description>
    <mmd:resource>{{ related_info['resource'] }}</mmd:resource>
  </mmd:related_information>
    {% endfor %}
  {% endif %}
```

The resource should be defined as `https://data.met.no/dataset/<uuid>` (for the prod env), so we just need to pick up that from the nc-file. When we ingest it to the catalog, dmci need to change the url to, e.g., `https://data-test.met.no/dataset/<uuid>` for the development environment.

I think you're also correct that it should be part of `dataset_citation > url` as well. As far as I understand from the docs, it can't be wrong to add it there :)

**Comment by mortenwh** [comment]
btw - in the DMH, we recommend people to use `metadata_link` for the `dataset_citation > url`. Not sure how to solve this. Should `dataset_citation > url` be the landing page? In that case, there are several options:

* The data producer sets `metadata_link = https://data.met.no/dataset/<uuid>`, and we just accept it (probably not a good idea)
* py-mmd-tools sets `self.metadata['dataset_citation']['url'] = self.metadata['related_information']['resource'] = https://data.met.no/dataset/<uuid>`, and does nothing with the nc-file attribute `metadata_link`
* py-mmd-tools sets `self.metadata['dataset_citation']['url'] = self.metadata['related_information']['resource'] = https://data.met.no/dataset/<uuid>`, and updates/sets the nc-file attribute `metadata_link`

Maybe @ferrighi can help to clarify?

**Comment by charlienegri** [comment]
I know nothing but the last option makes sense to me IF the field is not already there and filled at least.. like, what happens if that field is already present in the netcdf file and has been filled? check and overwrite anyway if namespace in metadata_identifier is no.met? or do not overwrite?

**Comment by mortenwh** [comment]
yes, the last option I mentioned was "update" but I changed it to "overwrite". That was indeed the case. But let's see what @ferrighi thinks first :)

**Comment by mortenwh** [comment]
I agree. Let's do all this in dmci, then.
