### ISSUE TITLE
netCDF requirements leading to ssl error on download of netcdf file

### ISSUE THREAD

**Issue by knl88** [metno/py-mmd-tools#230]
Hi,

I tried to open a dataset on a thredds server with nc2mmd, for example  running

```bash
nc2mmd -i https://thredds.met.no/thredds/dodsC/met.no/observations/stations/SN99935.nc -o .
```

but encountered an error
**Error:curl error: Problem with the SSL CA cert (path? access rights?)**

Think this is related to the requirements of the library `netCDF`  in the file [requirements.txt](https://github.com/metno/py-mmd-tools/blob/master/requirements.txt#L5), at least when I fix the requirement to `netCDF4==1.5.8`, the command works for me. Also the tests in this repos, except `tests/test_check_nc.py::test_failing_ncfile ` passes.

**Comment by mortenwh** [comment]
This is a bit strange, as all tests are passing in github actions. Can you give more details? Also, I advice you to run nc2mmd directly on the file, and not via opendap, as mentioned in another issue.

**Comment by knl88** [comment]
I get the error when running `nc2mmd` with `netCDF4==1.6.0`, the previous release works. Haven't looked too much into the details, but could be related to https://github.com/Unidata/netcdf4-python/issues/1199.  If so, it does not have to be a problem with the python lib.  Guess the tests patches the download.

**Comment by magnarem** [comment]
We have had similar issue. Netcdf/Curl cannot validate ca certs.

a possible solution is to create a file in your home directory called .ncrc and add this line:
HTTP.SSL.CAINFO=/etc/ssl/certs/ca-certificates.crt

**Comment by johtoblan** [comment]
Closed by adding solution to Readme, will later be fixed by using newer versions of NetCDF, which have this fixed as of june 2023
