### ISSUE TITLE
A new installation of py-mmd-tools does not work if vocab.met.no is down

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#231]
If vocab.met.no is down, it is usually not a problem because the vocabularies are cached. But if it is down when py-mmd-tools is installed, we can't cache anything and the tools will fail.

I see two possible solutions:

* have the lists in the git repo, perhaps also using actions to keep them updated
* make a service that people can use instead of installing it themselves

Anything else? Any opinions?

**Comment by johtoblan** [comment]
We have discussed service for py-mmd-tools before, and I think this will be the solution to use here. Though, whatever service we provide will be affected by downtime from met in probably the same way as vocab.met.no?

To the first point: We _can_ make vocabtools pull the source file, and integrate towards that, but seems like lots of work for very little reward (vocab.met.no doesn't usually go down)

**Comment by mortenwh** [comment]
We have now planned to make a nc-to-mmd service, so closing this.
