### ISSUE TITLE
nc2mmd requires http server when given an OPeNDAP url as input

### ISSUE THREAD

**Issue by knl88** [metno/py-mmd-tools#239]
When running  `nc2mmd`  on an OPeNDAP url  where the http server is not available the program fails with an error `urllib.error.HTTPError: HTTP Error 404`. This is because the program tries to download the file here https://github.com/metno/py-mmd-tools/blob/88498a9c1e4e97b21f79c23f01fecbebbe365887/py_mmd_tools/nc_to_mmd.py#L1245

**Comment by mortenwh** [comment]
You need to run it directly on the file, i.e., not via opendap. Also, the checksum calculation is disabled by default. There is no good solution for this at the moment but could be used at some point in relation to provenance documentation.
