### ISSUE TITLE
Different naming of organisation and datacenter.

### ISSUE THREAD

**Issue by magnarem** [metno/py-mmd-tools#241]
There are a few different naming of organisation and datacenter with the different products. Since all data in this product are from MET, then the registered names should ideally also be written the same way for all datasets.

The following screenshots will visualise this somehow.

![Screenshot 2023-03-15 at 17-32-20 Solr Admin.png](https://images.zenhubusercontent.com/5f3cf6176b958346b251d87a/331c500b-4bcf-4540-9585-be642458efcf)
![Screenshot 2023-03-15 at 17-22-35 Solr Admin.png](https://images.zenhubusercontent.com/5f3cf6176b958346b251d87a/571c2bae-edd2-43b0-928d-caa91328ea8c)
![Screenshot 2023-03-15 at 17-21-26 Solr Admin.png](https://images.zenhubusercontent.com/5f3cf6176b958346b251d87a/2b6aac98-65c2-4bbb-ba49-9312245ee910)
![Screenshot 2023-03-15 at 17-19-28 Solr Admin.png](https://images.zenhubusercontent.com/5f3cf6176b958346b251d87a/47bc1348-d0a5-414d-b3c3-5b5d1b7f3b21)

**Comment by mortenwh** [comment]
This could be handled by a config setting in the new API.

**Comment by mortenwh** [comment]
This is not really a problem anymore. It may happen but we'll catch issues quite fast. Also, the docs in DMH has improved.
