### ISSUE TITLE
WMS link should be added under data access

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#243]
We should be able to provide a custom url in replacement of a default ncwms (the one in thredds) url.

**Comment by johtoblan** [comment]
Need to be able to give a WMS link as input to the nc2mmd script, as of now the script will create one based on the OPENDAP URL

**Comment by TAlonglong** [comment]
Nice, I edit the mmd xml after creation to get the WMS link I want.

just a custom script, but is something I can look into.

**Comment by TAlonglong** [comment]
So I need some input here.

I assume the default is to generate ncwms link, where layer names are the variables in the netcdf file.

But the issue will add a custom link to a getcapabilities link. Thats fine, but how do we add the layers.

1. Add a command line option where the user specify which layers to add
2. Make a request for the getcapabilities document (xml) and parse this for available layers.

This first is simplest to implement. The second will be a major challenge as the for my case the products(ie. layers) are not generated the moment the netcdf is complete when the mmd generation is started. This will cause the mmd generation in best case to hang, but probably crash.

Please advise accordingly @johtoblan and @mortenwh (yeah, I know you are busy)
