### ISSUE TITLE
The ACDD attribute spatial_representation should follow controlled MMD vocabularies

### ISSUE THREAD

**Issue by shamlymajeed** [metno/py-mmd-tools#263]
We need to make custom functions to ensure that the right values are used.

The following attributes should be checked (plus maybe others - see the list in the Data Management Handbook):
- [x] spatial_representation

**Comment by johtoblan** [comment]
The controlled vocabulary is not in vocab.met.no

**Comment by mortenwh** [comment]
@ferrighi - can the MMD `spatial_representation` controlled vocabulary be added to vocab.met.no?

**Comment by ferrighi** [comment]
yes. It should be part of the vocabulary indeed.

**Comment by mortenwh** [comment]
@ferrighi - maybe this has been forgotten? Shall I make an issue in MMD?

**Comment by ferrighi** [comment]
Forgotten yes, sorry. Please make an issue in MMD.
