### ISSUE TITLE
Rewrite test_with_folder in test_nc2mmd_script

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mmd-tools#278]
https://github.com/metno/py-mmd-tools/blob/ac52a1f146ef2abaa43dce8b739b2dd75917875b/tests/test_nc2mmd_script.py#L152 
Tests whether reference_nc.xml has been created, because reference_nc_copy.xml is supposed to fail (Repeating IDs)
Different file systems will order these files differently, so this will fail on some filesystems.

The tests should either test for existence of only one of the files in folder or be rewritten in some other way.

**Comment by mortenwh** [comment]
Already solved in another issue
