### ISSUE TITLE
v2.2.0 is not backward compatible with v2.1.0

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#279]
/lustre/storeB/immutable/archive/projects/metproduction/DNMI_AROME_ARCTIC/2023/10/20/arome_arctic_lagged_12_h_subset_2_5km_20231020T18Z.nc:
```
	institution must be formed as <institution long name> (<institution short name>). Both are required attributes.
```
This seems to be a warning but the MMD is not created.

**Comment by mortenwh** [comment]
@charlienegri - could you take a look at this?

**Comment by charlienegri** [comment]
it comes from [L393 in nc_to_mmd.py,](https://github.com/metno/py-mmd-tools/blob/master/py_mmd_tools/nc_to_mmd.py#L393) is that not the expected behavior?

**Comment by johtoblan** [comment]
from ncdump -h:
```
		:institution_short_name = "MET Norway" ;
		:institution = "Norwegian Meteorological Institute" ;
```
