### ISSUE TITLE
Visualization of station data on data.met.no

### ISSUE THREAD

**Issue by mortenwh** [metno/py-mmd-tools#307]
Is it possible to add a link to the bokeh visualizations on station data available from data.met.no (currently only on the dev env)?

**Comment by magnarem** [comment]
Me and @ferrighi have discussed whethever feature type also should be a optional element in MMD. I do not know what we concluded in the discussion that I think we have talked about a handful of times.

**Comment by mortenwh** [comment]
Ok - but nothing under "data access", then? I guess this is ok if the related PR #308 helps enough...
