### ISSUE TITLE
SAFE to MMD

### ISSUE THREAD

**Issue by lhmarsden** [metno/py-mmd-tools#320]
In the NBS project we are interested in creating MMD products from our SAFE products (the usual format of sentinel products). This could be a useful contribution to this repository - though NBS is the only project I envisage using such a tool.

I will try to write a safe_to_mmd.py script in a forked repo and push a pull request to this repository.

**Comment by mortenwh** [comment]
@lhmarsden - what is the status on this?

**Comment by lhmarsden** [comment]
One of the students developed something over the summer to do this. I have not reviewed it yet. It will not be using py-mmd-tools.
