### ISSUE TITLE
Field "Personnel" for FROST stations datasets needs to be updated

### ISSUE THREAD

**Issue by ElodieFZ** [metno/py-mmd-tools#33]
Currently, it is

```
    <mmd:personnel>
        <mmd:role>Technical contact</mmd:role>
        <mmd:name>Ole Dole</mmd:name>
        <mmd:email>ole.dole@example.com</mmd:email>
        <mmd:phone>004711111111</mmd:phone>
        <mmd:fax/>
        <mmd:contact_address>
            <mmd:address>Meteorologisk institutt, Henrik Mohnsplass 1</mmd:address>
            <mmd:city>Oslo</mmd:city>
            <mmd:province_or_state>Oslo</mmd:province_or_state>
            <mmd:postal_code>0000</mmd:postal_code>
            <mmd:country>Norway</mmd:country>
        </mmd:contact_address>
    </mmd:personnel>
```

It needs to be updated with real contacts.

**Comment by ElodieFZ** [comment]
@niellaNina Can you tell me what to put as contact? Or tell me who to ask for this information?

**Comment by niellaNina** [comment]
This is the personnel we want to add:


   <mmd:personnel>
        <mmd:role>Technical contact</mmd:role>
        <mmd:name>Louise Oram</mmd:name>
        <mmd:email>observation_data_archive@met.no</mmd:email>
        <mmd:phone></mmd:phone>
        <mmd:fax/>
        <mmd:contact_address>
            <mmd:address>Meteorologisk institutt, Postboks 43 Blindern,</mmd:address>
            <mmd:city>Oslo</mmd:city>
            <mmd:province_or_state>Oslo</mmd:province_or_state>
            <mmd:postal_code>0313</mmd:postal_code>
            <mmd:country>Norway</mmd:country>
        </mmd:contact_address>
    </mmd:personnel>

<mmd:personnel>
        <mmd:role>Data center contact</mmd:role>
        <mmd:name>Vegar Kristiansen</mmd:name>
        <mmd:email>observation_data_archive@met.no</mmd:email>
        <mmd:phone></mmd:phone>
        <mmd:fax/>
        <mmd:contact_address>
            <mmd:address>Meteorologisk institutt, Postboks 43 Blindern,</mmd:address>
            <mmd:city>Oslo</mmd:city>
            <mmd:province_or_state>Oslo</mmd:province_or_state>
            <mmd:postal_code>0313</mmd:postal_code>
            <mmd:country>Norway</mmd:country>
        </mmd:contact_address>
    </mmd:personnel>

<mmd:personnel>
        <mmd:role>Metadata author</mmd:role>
        <mmd:name>Nina Larsgård</mmd:name>
        <mmd:email>observation_data_archive@met.no</mmd:email>
        <mmd:phone></mmd:phone>
        <mmd:fax/>
        <mmd:contact_address>
            <mmd:address>Meteorologisk institutt, Postboks 43 Blindern,</mmd:address>
            <mmd:city>Oslo</mmd:city>
            <mmd:province_or_state>Oslo</mmd:province_or_state>
            <mmd:postal_code>0313</mmd:postal_code>
            <mmd:country>Norway</mmd:country>
        </mmd:contact_address>
    </mmd:personnel>
