### ISSUE TITLE
Test location and naming convention

### ISSUE THREAD

**Issue by epifanio** [metno/py-mmd-tools#4]
I propose we store the test files in a dedicated directory and not in the source code module directory -  also propose  a naming convention like: `test_modulename.py` for the test files.

**Comment by mortenwh** [comment]
Ok - this will be solved in GH-3

**Comment by ElodieFZ** [comment]
Issue re-opened.
It has not been solved in https://github.com/metno/py-mmd-tools/pull/3 .
