### ISSUE TITLE
Request for new element in mmd_element.yaml

### ISSUE THREAD

**Issue by TAlonglong** [metno/py-mmd-tools#45]
According to Lara there is in INSPIRE need for "Party responsible for the metadata information" as a mandatory field.

That would be the "Metadata author" for mmd. Organization and email (email is mandatory) are needed at least

**Comment by mortenwh** [comment]
This should be solvable by adding the author as global attribute in the netcdf file using either 
```
creator_name, creator_role, creator_institution = <name>, 'Metadata author', <institution>
```
Or
```
contributor_name, contributor_role = <name>, 'Metadata author'
```
Can you check?

**Comment by TAlonglong** [comment]
We already use creator_<...> in netcdf:
```
                :creator_email = "post@met.no" ;
                :creator_name = "DIVISION FOR OBSERVATION QUALITY AND DATA PROCESSING" ;
                :creator_role = "Technical contact" ;
                :creator_type = "institution" ;
                :creator_url = "met.no" ;
```
That end up i mmd like this
```
  <mmd:personnel>
    <mmd:role>Technical contact</mmd:role>
    <mmd:name>DIVISION FOR OBSERVATION QUALITY AND DATA PROCESSING</mmd:name>
    <mmd:email>post@met.no</mmd:email>
    <mmd:phone></mmd:phone>
    <mmd:fax></mmd:fax>
    <mmd:organisation>unknown</mmd:organisation>
  </mmd:personnel>
```

**Comment by TAlonglong** [comment]
contributor_<...> does not seem to work

**Comment by TAlonglong** [comment]
This is need in #132

**Comment by mortenwh** [comment]
contributor_<--> is coming with https://app.zenhub.com/workspaces/s-enda-5e7b1b4acfc5ca185fb6b53c/issues/metno/py-mmd-tools/42

We may have to add email and organisation as ACDD extensions... What do you think?

**Comment by mortenwh** [comment]
this can be closed now, right?
