### ISSUE TITLE
extract mmd:storage_information/mmd:file_format

### ISSUE THREAD

**Issue by ferrighi** [metno/py-mmd-tools#50]
To  allow a full transformation to INSPIRE compliant file, the file format should be provided in mmd. The space for this is 
mmd:storage_information/mmd:file_format.

**Comment by TAlonglong** [comment]
I guess since this is to be included in the nc_to_mmd tool, we can assume storage_information netcdf?

Or will I also need to add some attribute to the netcdf files?

**Comment by ferrighi** [comment]
I think you shouldn't add anything. If the tool used to extract mmd is nc_to_mmd, the file_format is NetCDF-CF
